spring:  
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
       url: jdbc:mysql://localhost:3306/departmentDB    
       username: root
       password: Welcome123 

    
server:
    port: 8002    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
